version: '3'
services:
    smart: 
    image: smartplatform/3-3-snapshot:latest
        user: root
        ports:
            - "8100:3306"
            - "8081:80"
            - "9081:9081"
        volumes:
                - "./deploy-app:/app"
                - "./app-data:/var/lib/mysql"
        entrypoint: /bin/bash
        command:
            - /home/run.sh
        networks:
            front:
                ipv4_address: 172.16.238.10
                ipv6_address: "2001:3984:3989::10"

networks:
    front:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                - subnet: "2001:3984:3989::/64"

